Собрал проект с помощью вэбпака
next-ra/prj11 pull request #1
Opened 2020-02-03 01:10 UTC by next-ra

Разбил код на модули, добавил экспорты | импорты, пофиксил не закрывающиеся попапы, удалил лишние файлы и лишние комментарии с предыдущего ревью. Добавил файл readme с описанием проекта.

2020-02-03 07:09 UTC, aarefiev requested changes
Хорошая работа. В целом всё отлично.

Резюме: Есть все необходимые ветки (develop, build, production), проект выложен на github-pages, открывается, функционал на сайте работает. Ридми оформлено хорошо, но нет информации о том как развернуть проект. Игнорируются временные файлы. В самой работе используется **webpack**, есть файл `.nojekyll` настроено хэширование CSS и JS файлов, JS код транспилится в ES5, CSS минифицируется и проставляются префиксы.

Ниже я указал краткий список ошибок и улучшений, которые могут улучшить работу. Развернутые комментарии будут непосредственно в коде.

**Нужно исправить:**
1. Доработать README.

**Можно лучше:**
1. Вынести `targets` в отдельный файл.
2. Внедрить оптимизацию шрифтов: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=ru .

2020-02-03 07:09 UTC, aarefiev commented on README.md
> +### Проектная работа 11
Нужно исправить: доработать README.md.
Нужно указать в описании:
- версию,
- информацию о том, как развернуть проект

В дополнение к ссылкам из практики рекомендую почитать статью "[Как написать хороший README?](https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26)". Примеры шаблонов для README:
- https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
- https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

2020-02-03 07:09 UTC, aarefiev commented on babel.config.js
> +        },
Можно лучше: вынести `targets` в отдельный файл.
Благодаря использованию https://github.com/browserslist/browserslist можно задать единые параметры поддержки для многих инструментов, таких как: babel, autoprefixer и другие.

2020-02-07 22:30 UTC, next-ra commented
Отредактировал файл readme, добавил browserlist в package.json, добавил оптимизацию шрифтов

2020-02-08 08:20 UTC, aarefiev approved these changes
Отлично, принято 🎉 .
Запускаем 🚀

2020-02-08 08:20 UTC, aarefiev commented on package.json
> +  "scripts": {
Можно лучше: следить за форматированием.
Когда весь код отформатирован в одном стиле, то читается лучше.
И здесь тоже:
https://github.com/next-ra/prj11/blob/c81678f85475cf65e4a516b7dc7d8e4442c70ba5/src/vendor/fonts.css#L1-L10

2020-02-08 08:20 UTC, aarefiev commented on package.json
> +    "build": "cross-env NODE_ENV=production rimraf dist && webpack --mode production",
🦀 Понятно, что этот код был взят как есть из практики, поэтому не отношу его ни к одной из секций. 🦀 

Если залогировать значение `process.env.NODE_ENV` в `webpack.config.js` мы получим следующее:
```bash
$ npm run build

> praktikum-project11@1.0.1 build ~/prj11
> cross-env NODE_ENV=production rimraf dist && webpack --mode production

{ NODE_ENV: undefined }
```

Это связано с тем, что при выполнении команды `npm run build` будет выполнено 2-е команды последовательно (они соединены через `&&`):
1. `cross-env NODE_ENV=production rimraf dist`.
2. `webpack --mode production`

Видно, что ENV переменная не передается 2-й команде соответственно в коде `process.env.NODE_ENV` равен `undefined`. 

Чтобы работало, нужно `cross-env NODE_ENV=production` перенести во вторую команду:
```suggestion
    "build": "rimraf dist && cross-env NODE_ENV=production webpack --mode production",
```

Результаты выполнения:
```bash
$ npm run build

> praktikum-project11@1.0.1 build ~/prj11
> rimraf dist && cross-env NODE_ENV=production webpack --mode production

{ NODE_ENV: 'production' }
```

2020-02-08 09:11 UTC, merged